version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gerador-backend
    env_file:
      - ./backend/.env       
    volumes:
      - ./backend:/app          
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile   
    container_name: gerador-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules        
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
